=== yschiebelhut/Geburtstagskalender/backend/birthdays.dtd
<!ELEMENT birthdays (monthname,bday*)>
<!ELEMENT monthname (#PCDATA)>
<!ELEMENT bday (id,name,day,month,year,notes)>
<!ELEMENT id (#PCDATA)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT day (#PCDATA)>
<!ELEMENT month (#PCDATA)>
<!ELEMENT year (#PCDATA)>
<!ELEMENT notes (#PCDATA)>

=== yschiebelhut/Geburtstagskalender/backend/test.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="xslt/test.xsl"?>
<!DOCTYPE birthdays SYSTEM "birthdays.dtd">
<birthdays>
	<monthname>June</monthname>
	<bday>
		<id>7</id>
		<name>A</name>
		<day>10</day>
		<month>6</month>
		<year/>
		<notes/>
	</bday>
	<bday>
		<id>8</id>
		<name>B</name>
		<day>12</day>
		<month>6</month>
		<year>2002</year>
		<notes/>
	</bday>
</birthdays>

=== yschiebelhut/Geburtstagskalender/backend/birthdays-test.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="/frontend/xslt/listview.xsl"?>
<!DOCTYPE birthdays SYSTEM "birthdays.dtd">
<birthdays>
    <monthname>June</monthname>
    <year>2021</year>
    <bday>
        <daysleft>-25</daysleft>
        <id>7</id>
        <name>A</name>
        <day>10</day>
        <month>6</month>
        <year/>
        <notes/>
    </bday>
    <bday>
        <daysleft>-23</daysleft>
        <id>8</id>
        <name>B</name>
        <day>12</day>
        <month>6</month>
        <year/>
        <notes/>
    </bday>
</birthdays>
