=== yschiebelhut/Geburtstagskalender/backend/calendar.dtd
<!ELEMENT calendar (now, monthname, year, row*)>
<!ELEMENT now (day, monthname, year)>
<!ELEMENT row (entry*)>
<!ELEMENT entry ((index, inMonth, bday*) | (inMonth))>
<!ELEMENT bday (daysleft,id,name,day,month,year,notes)>
<!ELEMENT daysleft (#PCDATA)>
<!ELEMENT id (#PCDATA)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT day (#PCDATA)>
<!ELEMENT month (#PCDATA)>
<!ELEMENT year (#PCDATA)>
<!ELEMENT notes (#PCDATA)>
<!ELEMENT index (#PCDATA)>
<!ELEMENT inMonth (#PCDATA)>
<!ELEMENT monthname (#PCDATA)>

=== yschiebelhut/Geburtstagskalender/backend/calendarview-test.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="/frontend/xslt/calendarview.xsl"?>
<!DOCTYPE calendar SYSTEM "calendar.dtd">
<calendar>
    <monthname>July</monthname>
    <year>2021</year>
    <row>
        <entry>
            <inMonth>false</inMonth>
        </entry>
        <entry>
            <inMonth>false</inMonth>
        </entry>
        <entry>
            <inMonth>false</inMonth>
        </entry>
        <entry>
            <index>1</index>
            <inMonth>true</inMonth>
        </entry>
        <entry>
            <index>2</index>
            <inMonth>true</inMonth>
        </entry>
        <entry>
            <index>3</index>
            <inMonth>true</inMonth>
        </entry>
        <entry>
            <index>4</index>
            <inMonth>true</inMonth>
        </entry>
    </row>
    <row>
        <entry>
            <index>5</index>
            <inMonth>true</inMonth>
        </entry>
        <entry>
            <index>6</index>
            <inMonth>true</inMonth>
        </entry>
        <entry>
            <index>7</index>
            <inMonth>true</inMonth>
        </entry>
        <entry>
            <index>8</index>
            <inMonth>true</inMonth>
        </entry>
        <entry>
            <index>9</index>
            <inMonth>true</inMonth>
        </entry>
        <entry>
            <index>10</index>
            <inMonth>true</inMonth>
            <bday>
                <daysleft>5</daysleft>
                <id>9</id>
                <name>A</name>
                <day>10</day>
                <month>7</month>
                <year/>
                <notes/>
            </bday>
        </entry>
        <entry>
            <index>11</index>
            <inMonth>true</inMonth>
        </entry>
    </row>
    <row>
        <entry>
            <index>12</index>
            <inMonth>true</inMonth>
        </entry>
        <entry>
            <index>13</index>
            <inMonth>true</inMonth>
        </entry>
        <entry>
            <index>14</index>
            <inMonth>true</inMonth>
        </entry>
        <entry>
            <index>15</index>
            <inMonth>true</inMonth>
        </entry>
        <entry>
            <index>16</index>
            <inMonth>true</inMonth>
        </entry>
        <entry>
            <index>17</index>
            <inMonth>true</inMonth>
        </entry>
        <entry>
            <index>18</index>
            <inMonth>true</inMonth>
        </entry>
    </row>
    <row>
        <entry>
            <index>19</index>
            <inMonth>true</inMonth>
        </entry>
        <entry>
            <index>20</index>
            <inMonth>true</inMonth>
        </entry>
        <entry>
            <index>21</index>
            <inMonth>true</inMonth>
        </entry>
        <entry>
            <index>22</index>
            <inMonth>true</inMonth>
        </entry>
        <entry>
            <index>23</index>
            <inMonth>true</inMonth>
        </entry>
        <entry>
            <index>24</index>
            <inMonth>true</inMonth>
        </entry>
        <entry>
            <index>25</index>
            <inMonth>true</inMonth>
        </entry>
    </row>
    <row>
        <entry>
            <index>26</index>
            <inMonth>true</inMonth>
        </entry>
        <entry>
            <index>27</index>
            <inMonth>true</inMonth>
        </entry>
        <entry>
            <index>28</index>
            <inMonth>true</inMonth>
        </entry>
        <entry>
            <index>29</index>
            <inMonth>true</inMonth>
        </entry>
        <entry>
            <index>30</index>
            <inMonth>true</inMonth>
        </entry>
        <entry>
            <index>31</index>
            <inMonth>true</inMonth>
        </entry>
        <entry>
            <inMonth>false</inMonth>
        </entry>
    </row>
</calendar>
